---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: cloudflarerecord
  name: cloudflarerecords.controllers.illallangi.enterprises
spec:
  group: controllers.illallangi.enterprises
  names:
    kind: CloudFlareRecord
    plural: cloudflarerecords
    shortNames:
    - cloudflare
    singular: cloudflarerecord
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Age of the DNS Record
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            items:
              properties:
                fqdn:
                  type: string
                zoneID:
                  type: string
              required:
              - fqdn
              - zoneID
              type: object
            type: array
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        required:
        - spec
        type: object
    served: true
    storage: true
